version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    #working_directory: ~/gls # directory where steps will run
    docker: # run the steps with Docker
      - image: tabookey/eth-tools:1.0

    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-yarn1
      - run:
          name: yarn-install
          command: yarn

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-yarn1
          paths:
            - ./node_modules

      - run: # run tests
          name: test
          command: npm test

